### ISSUE TITLE
Font color of the menus is unchanged from white and affects visibility!

### ISSUE THREAD

**Issue by SubhamBurnwal** [raniaamina/libreoffice-theme#8]
This is consistent across all themes, be it the default ones, or from this project, and it was actually one of the reasons I had to look for a theme customizer. Please help.

**Comment by raniaamina** [comment]
Can you provide more informations, screenshot, etc?

**Comment by SubhamBurnwal** [comment]
With one of these themes..
![Screenshot from 2021-02-01 05-31-03](https://user-images.githubusercontent.com/36904784/106402320-f5dc1500-644e-11eb-9fd1-47053b26c77e.png)
With the default "White" theme..
![Screenshot from 2021-02-01 05-23-50](https://user-images.githubusercontent.com/36904784/106402100-f58f4a00-644d-11eb-892c-67584e00861e.png)
Now I guess it is a bug in LibreOffice's own code, not here..

**Comment by raniaamina** [comment]
Ah, i see. That's why we alsop provide two kind of thmes. . Lilight anh dark theme for this problem.

**Comment by SubhamBurnwal** [comment]
So I just forgot to download the dark one? Kindly name the folder and tell
me what can be done to extend the theme to cover the whole application
instead of just headers footers and icons. I didn't find this in the
documentation, and you sir probably are sitting on all the research already
:P
If wish to contribute if I can
